export const LOGIN = 'LOGIN';
export const LOGIN_UNSUCCESS = 'LOGIN_UNSUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const RESEND = 'RESEND';
export const RESEND_SUCCESS = 'RESEND';
export const RESEND_FAIL = 'RESEND';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_UNSUCCESS = 'USER_UPDATE_UNSUCCESS';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_UNSUCCESS = 'SIGNUP_UNSUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
